# Uses a Node.js base image
FROM node:14
 
# Set the working directory within the container
WORKDIR /app
 
COPY package.json package-lock.json ./
 
# Install dependencies
RUN npm install --production
 
# Copy the rest of the project files to the working directory
COPY . .
 
# Expose the port in the container 
EXPOSE 3001
 
# Command to run the application when the container is started
CMD ["node", "app.js"]