name: Build and Push Docker images
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
 
      - name: Build and push Microservicio_Clima
        uses: docker/build-push-action@v2
        with:
          context: ./Microservicio_Clima
          file: ./Microservicio_Clima/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservicio_clima:latest
 
      - name: Build and push Nasa
        uses: docker/build-push-action@v2
        with:
          context: ./Nasa
          file: ./Nasa/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nasa:latest
 
      - name: Build and push NasaImagen
        uses: docker/build-push-action@v2
        with:
          context: ./NasaImagen
          file: ./NasaImagen/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nasaimagen:latest