name: Build and Push Docker images
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
 
      - name: Build and push Microservicio_Clima
        uses: docker/build-push-action@v2
        with:
          context: ./Microservicio_Clima
          file: ./Microservicio_Clima/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservicio_clima:latest
 
      - name: Build and push Nasa
        uses: docker/build-push-action@v2
        with:
          context: ./Nasa
          file: ./Nasa/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nasa:latest
 
      - name: Build and push NasaImagen
        uses: docker/build-push-action@v2
        with:
          context: ./NasaImagen
          file: ./NasaImagen/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nasaimagen:latest


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/microservicio_clima:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/nasa:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/nasaimagen:latest
            docker stop microservicio_clima || true
            docker stop nasa || true
            docker stop nasaimagen || true
            docker rm microservicio_clima || true
            docker rm nasa || true
            docker rm nasaimagen || true
            docker run -d --name microservicio_clima -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/microservicio_clima:latest
            docker run -d --nasas -p 3002:3002 ${{ secrets.DOCKER_USERNAME }}/nasa:latest
            docker run -d --name nasaimagen -p 3003:3003 ${{ secrets.DOCKER_USERNAME }}/nasaimagen:latest
