# Use the Node.js base image with the version you are using in your project.
FROM node:14

# Sets the working directory inside the container
WORKDIR /usr/src/app


COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3003

# Command to run your application when the container starts up
CMD ["node", "app.js"]
